[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=src --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]

[tool.pylint]
init-hook = "import sys; sys.path.append('src')"
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


